# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43da9722b8161d3165c5e83a0210a31547f0a1ceba89ada7ee7b07a063bed7f82e1dbaeb04df5bf5a7a4f48548ca270682109dbfe3e05e99088416e4f532c4e0

test:
  secret_key_base: 9a9b4ce5a73f90877f347e9d3b432ad459af6d63601372ba6db295ec33df2e52ff260e9d6e92b1d288ec5041a7e14a306268cd77e19eb9a7e017029fba162e7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
